  101-funcion-de-eliminar-me-interesa[m
  102-arreglar-refresco-de-página[m
  103-usuarios-en-panel-de-administrador[m
  104-lista-de-favoritos-para-usuario[m
  105-actualización-de-usuario[m
  107-ajustar-interacción[m
  109-ajustar-boton-me-interesa-en-frontend[m
  123-back-generador-de-códigos-qr[m
  124-back-transición-de-estado[m
  126-back-endpoints-de-dshboard-y-reporte[m
  127-front-admin-interfaz-de-tipos-de-entrada[m
  128-front-admin-gestion-de-aforo-por-evento[m
  129-front-admin-dashboard-estadístico[m
  130-front-admin-generador-de-reportes[m
  133-front-cliente-vista-mis-boletas[m
  135-repositorio-añadir-ci[m
  145-back-eliminar-usuario[m
  160-front-opción-para-eliminar-cuenta-usuario[m
  165-back-implementar-autenticacion-a-las-rutas-de-tickets[m
  170-back-endpoint-total-boletas-usuario[m
  175-arreglar-ingreso-a-eventos-inhabilitados[m
  186-front-separar-modulo-de-dashboard[m
  192-compra-multiple[m
* [32m195-interfaz-de-pago[m
  2-crear-modelo-de-datos[m
  25-dockerizar-base-de-datos[m
  35-adaptar-esquema-backend[m
  37-crud-de-categorias-en-backend[m
  39-gestion-de-categorías-en-frontend[m
  40-validar-restricciones-del-formulario[m
  46-modificar-script-base-de-datos[m
  47-implementar-script-de-creacion[m
  48-modificar-edicion-de-evento-front[m
  49-implementar-readme[m
  62-modificar-esquema-de-base-de-datos[m
  65-query-de-reporte-de-favoritos[m
  67-panel-de-reportes-para-administrador[m
  79-implementar-nueva-logica-en-backend[m
  main[m
